# Title of your blog; shows in the header
name: "king context"

# Description of your content (will only be used on Google Search)
description: "king context"

# Your name. Will show in your footer + sidebar 
owner: "Jan Uyttenhove"

author: "King Context"

url: "http://www.kingcontext.com"
baseurl: ""

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words. 
author-bio-p1: "Context is king. This is King Context."
author-bio-p2: "It's all about data here!!"

# Social Accounts

twitter: xorto
github: kingcontext
linkedin: januyttenhove
#dribbble: m3xm
#instagram: m3xm

# Google Analytics (you may want to changes these with yours or even delete :)

ga_domain: auto
ga_tracking_id: UA-66832385-1

# Other (refer to http://jekyllrb.com/docs/home/ for further details on the below)

markdown: kramdown
permalink: pretty
highlighter: pygments

paginate: 10
paginate_path: "/page/:num"

# SCSS

sass:
  sass_dir: _scss
  style: :compressed
